### ISSUE TITLE
WHY IS EVERYTHING GONE NOW?????

### ISSUE THREAD

**Issue by MethanJess** [metame-ai/awesome-audio-plaza#3]
Everything in the Readme has been almost entirely removed, why??
![Screenshot 2024-10-26 184805](https://github.com/user-attachments/assets/09869e24-de3b-42b5-bbd1-792125da1f89)

**Comment by metame-none** [comment]
<img width="920" alt="image" src="https://github.com/user-attachments/assets/48206a07-3b84-42c7-a041-8c5a2a484e0e">
hi, it's not gone. I re-orged, and the old docs is moved to 'part1' dir.
